# These are supported funding model platforms

# GitHub Sponsors
github: [jacar-javi]

# Buy me a Coffee
buy_me_a_coffee: jacar

# Patreon
# patreon: your-username

# Open Collective
# open_collective: jacommander

# Ko-fi
# ko_fi: your-username

# Tidelift
# tidelift: npm/jacommander

# Community Bridge
# community_bridge: jacommander

# Liberapay
# liberapay: your-username

# IssueHunt
# issuehunt: jacar-javi/jacommander

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/your-username']
