// language-pack.js - Extended language translations for JaCommander
export const languagePack = {
    // French
    fr: {
        // Header
        'app.title': 'JaCommander',
        menu: 'Menu',
        'keyboard.shortcuts': 'Raccourcis clavier',
        configuration: 'Configuration',
        'toggle.theme': 'Changer de thème',

        // Footer buttons
        'f1.help': 'F1 Aide',
        'f2.menu': 'F2 Menu',
        'f3.view': 'F3 Voir',
        'f4.edit': 'F4 Éditer',
        'f5.copy': 'F5 Copier',
        'f6.move': 'F6 Déplacer',
        'f7.mkdir': 'F7 Dossier',
        'f8.delete': 'F8 Supprimer',
        'f9.menu': 'F9 Menu',
        'f10.exit': 'F10 Quitter',
        'f11.terminal': 'F11 Terminal',
        'f12.settings': 'F12 Paramètres',

        // Panel headers
        name: 'Nom',
        size: 'Taille',
        modified: 'Modifié',
        items: 'éléments',
        selected: 'sélectionné',

        // Operations
        copy: 'Copier',
        move: 'Déplacer',
        delete: 'Supprimer',
        rename: 'Renommer',
        'new.folder': 'Nouveau dossier',
        'new.file': 'Nouveau fichier',
        refresh: 'Actualiser',
        search: 'Rechercher',
        'select.all': 'Tout sélectionner',
        'deselect.all': 'Tout désélectionner',

        // File operations
        copying: 'Copie en cours',
        moving: 'Déplacement en cours',
        deleting: 'Suppression en cours',
        creating: 'Création en cours',
        extracting: 'Extraction en cours',
        compressing: 'Compression en cours',

        // Dialogs
        confirm: 'Confirmer',
        cancel: 'Annuler',
        ok: 'OK',
        yes: 'Oui',
        no: 'Non',
        error: 'Erreur',
        warning: 'Avertissement',
        info: 'Information',
        success: 'Succès',

        // Messages
        'file.exists': 'Le fichier existe déjà',
        'overwrite.confirm': 'Voulez-vous écraser?',
        'delete.confirm': 'Êtes-vous sûr de vouloir supprimer?',
        'operation.complete': 'Opération terminée',
        'operation.failed': 'Opération échouée',

        // Context menu
        open: 'Ouvrir',
        'open.with': 'Ouvrir avec',
        cut: 'Couper',
        'copy.to': 'Copier vers',
        'move.to': 'Déplacer vers',
        properties: 'Propriétés',

        // Search
        'search.placeholder': 'Rechercher des fichiers...',
        'search.results': 'Résultats de recherche',
        'no.results': 'Aucun résultat trouvé',

        // Settings
        settings: 'Paramètres',
        language: 'Langue',
        theme: 'Thème',
        'font.size': 'Taille de police',
        'show.hidden': 'Afficher les fichiers cachés',
        'confirm.delete': 'Confirmer la suppression',
        save: 'Enregistrer',

        // Terminal
        terminal: 'Terminal',
        clear: 'Effacer',
        close: 'Fermer'
    },

    // Italian
    it: {
        'app.title': 'JaCommander',
        menu: 'Menu',
        'keyboard.shortcuts': 'Scorciatoie da tastiera',
        configuration: 'Configurazione',
        'toggle.theme': 'Cambia tema',
        'f1.help': 'F1 Aiuto',
        'f2.menu': 'F2 Menu',
        'f3.view': 'F3 Visualizza',
        'f4.edit': 'F4 Modifica',
        'f5.copy': 'F5 Copia',
        'f6.move': 'F6 Sposta',
        'f7.mkdir': 'F7 Cartella',
        'f8.delete': 'F8 Elimina',
        'f9.menu': 'F9 Menu',
        'f10.exit': 'F10 Esci',
        'f11.terminal': 'F11 Terminale',
        'f12.settings': 'F12 Impostazioni',
        name: 'Nome',
        size: 'Dimensione',
        modified: 'Modificato',
        items: 'elementi',
        selected: 'selezionato',
        copy: 'Copia',
        move: 'Sposta',
        delete: 'Elimina',
        rename: 'Rinomina',
        'new.folder': 'Nuova cartella',
        'new.file': 'Nuovo file',
        refresh: 'Aggiorna',
        search: 'Cerca',
        'select.all': 'Seleziona tutto',
        'deselect.all': 'Deseleziona tutto',
        copying: 'Copia in corso',
        moving: 'Spostamento in corso',
        deleting: 'Eliminazione in corso',
        creating: 'Creazione in corso',
        extracting: 'Estrazione in corso',
        compressing: 'Compressione in corso',
        confirm: 'Conferma',
        cancel: 'Annulla',
        ok: 'OK',
        yes: 'Sì',
        no: 'No',
        error: 'Errore',
        warning: 'Avviso',
        info: 'Informazione',
        success: 'Successo',
        'file.exists': 'Il file esiste già',
        'overwrite.confirm': 'Vuoi sovrascrivere?',
        'delete.confirm': 'Sei sicuro di voler eliminare?',
        'operation.complete': 'Operazione completata',
        'operation.failed': 'Operazione fallita',
        open: 'Apri',
        'open.with': 'Apri con',
        cut: 'Taglia',
        'copy.to': 'Copia in',
        'move.to': 'Sposta in',
        properties: 'Proprietà',
        'search.placeholder': 'Cerca file...',
        'search.results': 'Risultati ricerca',
        'no.results': 'Nessun risultato trovato',
        settings: 'Impostazioni',
        language: 'Lingua',
        theme: 'Tema',
        'font.size': 'Dimensione font',
        'show.hidden': 'Mostra file nascosti',
        'confirm.delete': 'Conferma eliminazione',
        save: 'Salva',
        terminal: 'Terminale',
        clear: 'Cancella',
        close: 'Chiudi'
    },

    // Portuguese
    pt: {
        'app.title': 'JaCommander',
        menu: 'Menu',
        'keyboard.shortcuts': 'Atalhos de teclado',
        configuration: 'Configuração',
        'toggle.theme': 'Alternar tema',
        'f1.help': 'F1 Ajuda',
        'f2.menu': 'F2 Menu',
        'f3.view': 'F3 Ver',
        'f4.edit': 'F4 Editar',
        'f5.copy': 'F5 Copiar',
        'f6.move': 'F6 Mover',
        'f7.mkdir': 'F7 Pasta',
        'f8.delete': 'F8 Apagar',
        'f9.menu': 'F9 Menu',
        'f10.exit': 'F10 Sair',
        'f11.terminal': 'F11 Terminal',
        'f12.settings': 'F12 Configurações',
        name: 'Nome',
        size: 'Tamanho',
        modified: 'Modificado',
        items: 'itens',
        selected: 'selecionado',
        copy: 'Copiar',
        move: 'Mover',
        delete: 'Apagar',
        rename: 'Renomear',
        'new.folder': 'Nova pasta',
        'new.file': 'Novo arquivo',
        refresh: 'Atualizar',
        search: 'Buscar',
        'select.all': 'Selecionar tudo',
        'deselect.all': 'Desselecionar tudo',
        copying: 'Copiando',
        moving: 'Movendo',
        deleting: 'Apagando',
        creating: 'Criando',
        extracting: 'Extraindo',
        compressing: 'Comprimindo',
        confirm: 'Confirmar',
        cancel: 'Cancelar',
        ok: 'OK',
        yes: 'Sim',
        no: 'Não',
        error: 'Erro',
        warning: 'Aviso',
        info: 'Informação',
        success: 'Sucesso',
        'file.exists': 'Arquivo já existe',
        'overwrite.confirm': 'Deseja sobrescrever?',
        'delete.confirm': 'Tem certeza que deseja apagar?',
        'operation.complete': 'Operação concluída',
        'operation.failed': 'Operação falhou',
        open: 'Abrir',
        'open.with': 'Abrir com',
        cut: 'Cortar',
        'copy.to': 'Copiar para',
        'move.to': 'Mover para',
        properties: 'Propriedades',
        'search.placeholder': 'Buscar arquivos...',
        'search.results': 'Resultados da busca',
        'no.results': 'Nenhum resultado encontrado',
        settings: 'Configurações',
        language: 'Idioma',
        theme: 'Tema',
        'font.size': 'Tamanho da fonte',
        'show.hidden': 'Mostrar arquivos ocultos',
        'confirm.delete': 'Confirmar exclusão',
        save: 'Salvar',
        terminal: 'Terminal',
        clear: 'Limpar',
        close: 'Fechar'
    },

    // Russian
    ru: {
        'app.title': 'JaCommander',
        menu: 'Меню',
        'keyboard.shortcuts': 'Горячие клавиши',
        configuration: 'Конфигурация',
        'toggle.theme': 'Сменить тему',
        'f1.help': 'F1 Помощь',
        'f2.menu': 'F2 Меню',
        'f3.view': 'F3 Просмотр',
        'f4.edit': 'F4 Правка',
        'f5.copy': 'F5 Копировать',
        'f6.move': 'F6 Переместить',
        'f7.mkdir': 'F7 Папка',
        'f8.delete': 'F8 Удалить',
        'f9.menu': 'F9 Меню',
        'f10.exit': 'F10 Выход',
        'f11.terminal': 'F11 Терминал',
        'f12.settings': 'F12 Настройки',
        name: 'Имя',
        size: 'Размер',
        modified: 'Изменен',
        items: 'элементов',
        selected: 'выбрано',
        copy: 'Копировать',
        move: 'Переместить',
        delete: 'Удалить',
        rename: 'Переименовать',
        'new.folder': 'Новая папка',
        'new.file': 'Новый файл',
        refresh: 'Обновить',
        search: 'Поиск',
        'select.all': 'Выбрать все',
        'deselect.all': 'Снять выбор',
        copying: 'Копирование',
        moving: 'Перемещение',
        deleting: 'Удаление',
        creating: 'Создание',
        extracting: 'Извлечение',
        compressing: 'Сжатие',
        confirm: 'Подтвердить',
        cancel: 'Отмена',
        ok: 'ОК',
        yes: 'Да',
        no: 'Нет',
        error: 'Ошибка',
        warning: 'Предупреждение',
        info: 'Информация',
        success: 'Успех',
        'file.exists': 'Файл уже существует',
        'overwrite.confirm': 'Хотите перезаписать?',
        'delete.confirm': 'Вы уверены, что хотите удалить?',
        'operation.complete': 'Операция завершена',
        'operation.failed': 'Операция не удалась',
        open: 'Открыть',
        'open.with': 'Открыть с помощью',
        cut: 'Вырезать',
        'copy.to': 'Копировать в',
        'move.to': 'Переместить в',
        properties: 'Свойства',
        'search.placeholder': 'Поиск файлов...',
        'search.results': 'Результаты поиска',
        'no.results': 'Результатов не найдено',
        settings: 'Настройки',
        language: 'Язык',
        theme: 'Тема',
        'font.size': 'Размер шрифта',
        'show.hidden': 'Показать скрытые файлы',
        'confirm.delete': 'Подтвердить удаление',
        save: 'Сохранить',
        terminal: 'Терминал',
        clear: 'Очистить',
        close: 'Закрыть'
    },

    // Chinese Simplified
    zh: {
        'app.title': 'JaCommander',
        menu: '菜单',
        'keyboard.shortcuts': '快捷键',
        configuration: '配置',
        'toggle.theme': '切换主题',
        'f1.help': 'F1 帮助',
        'f2.menu': 'F2 菜单',
        'f3.view': 'F3 查看',
        'f4.edit': 'F4 编辑',
        'f5.copy': 'F5 复制',
        'f6.move': 'F6 移动',
        'f7.mkdir': 'F7 新建文件夹',
        'f8.delete': 'F8 删除',
        'f9.menu': 'F9 菜单',
        'f10.exit': 'F10 退出',
        'f11.terminal': 'F11 终端',
        'f12.settings': 'F12 设置',
        name: '名称',
        size: '大小',
        modified: '修改时间',
        items: '项',
        selected: '已选择',
        copy: '复制',
        move: '移动',
        delete: '删除',
        rename: '重命名',
        'new.folder': '新建文件夹',
        'new.file': '新建文件',
        refresh: '刷新',
        search: '搜索',
        'select.all': '全选',
        'deselect.all': '取消全选',
        copying: '正在复制',
        moving: '正在移动',
        deleting: '正在删除',
        creating: '正在创建',
        extracting: '正在解压',
        compressing: '正在压缩',
        confirm: '确认',
        cancel: '取消',
        ok: '确定',
        yes: '是',
        no: '否',
        error: '错误',
        warning: '警告',
        info: '信息',
        success: '成功',
        'file.exists': '文件已存在',
        'overwrite.confirm': '是否要覆盖？',
        'delete.confirm': '确定要删除吗？',
        'operation.complete': '操作完成',
        'operation.failed': '操作失败',
        open: '打开',
        'open.with': '打开方式',
        cut: '剪切',
        'copy.to': '复制到',
        'move.to': '移动到',
        properties: '属性',
        'search.placeholder': '搜索文件...',
        'search.results': '搜索结果',
        'no.results': '未找到结果',
        settings: '设置',
        language: '语言',
        theme: '主题',
        'font.size': '字体大小',
        'show.hidden': '显示隐藏文件',
        'confirm.delete': '确认删除',
        save: '保存',
        terminal: '终端',
        clear: '清除',
        close: '关闭'
    },

    // Japanese
    ja: {
        'app.title': 'JaCommander',
        menu: 'メニュー',
        'keyboard.shortcuts': 'キーボードショートカット',
        configuration: '設定',
        'toggle.theme': 'テーマ切替',
        'f1.help': 'F1 ヘルプ',
        'f2.menu': 'F2 メニュー',
        'f3.view': 'F3 表示',
        'f4.edit': 'F4 編集',
        'f5.copy': 'F5 コピー',
        'f6.move': 'F6 移動',
        'f7.mkdir': 'F7 新規フォルダ',
        'f8.delete': 'F8 削除',
        'f9.menu': 'F9 メニュー',
        'f10.exit': 'F10 終了',
        'f11.terminal': 'F11 ターミナル',
        'f12.settings': 'F12 設定',
        name: '名前',
        size: 'サイズ',
        modified: '更新日時',
        items: '項目',
        selected: '選択済み',
        copy: 'コピー',
        move: '移動',
        delete: '削除',
        rename: '名前変更',
        'new.folder': '新規フォルダ',
        'new.file': '新規ファイル',
        refresh: '更新',
        search: '検索',
        'select.all': 'すべて選択',
        'deselect.all': 'すべて選択解除',
        copying: 'コピー中',
        moving: '移動中',
        deleting: '削除中',
        creating: '作成中',
        extracting: '解凍中',
        compressing: '圧縮中',
        confirm: '確認',
        cancel: 'キャンセル',
        ok: 'OK',
        yes: 'はい',
        no: 'いいえ',
        error: 'エラー',
        warning: '警告',
        info: '情報',
        success: '成功',
        'file.exists': 'ファイルは既に存在します',
        'overwrite.confirm': '上書きしますか？',
        'delete.confirm': '削除してもよろしいですか？',
        'operation.complete': '操作完了',
        'operation.failed': '操作失敗',
        open: '開く',
        'open.with': 'プログラムから開く',
        cut: '切り取り',
        'copy.to': 'コピー先',
        'move.to': '移動先',
        properties: 'プロパティ',
        'search.placeholder': 'ファイル検索...',
        'search.results': '検索結果',
        'no.results': '結果が見つかりません',
        settings: '設定',
        language: '言語',
        theme: 'テーマ',
        'font.size': 'フォントサイズ',
        'show.hidden': '隠しファイル表示',
        'confirm.delete': '削除確認',
        save: '保存',
        terminal: 'ターミナル',
        clear: 'クリア',
        close: '閉じる'
    },

    // Korean
    ko: {
        'app.title': 'JaCommander',
        menu: '메뉴',
        'keyboard.shortcuts': '키보드 단축키',
        configuration: '설정',
        'toggle.theme': '테마 전환',
        'f1.help': 'F1 도움말',
        'f2.menu': 'F2 메뉴',
        'f3.view': 'F3 보기',
        'f4.edit': 'F4 편집',
        'f5.copy': 'F5 복사',
        'f6.move': 'F6 이동',
        'f7.mkdir': 'F7 새 폴더',
        'f8.delete': 'F8 삭제',
        'f9.menu': 'F9 메뉴',
        'f10.exit': 'F10 종료',
        'f11.terminal': 'F11 터미널',
        'f12.settings': 'F12 설정',
        name: '이름',
        size: '크기',
        modified: '수정됨',
        items: '항목',
        selected: '선택됨',
        copy: '복사',
        move: '이동',
        delete: '삭제',
        rename: '이름 변경',
        'new.folder': '새 폴더',
        'new.file': '새 파일',
        refresh: '새로고침',
        search: '검색',
        'select.all': '모두 선택',
        'deselect.all': '모두 선택 해제',
        copying: '복사 중',
        moving: '이동 중',
        deleting: '삭제 중',
        creating: '생성 중',
        extracting: '추출 중',
        compressing: '압축 중',
        confirm: '확인',
        cancel: '취소',
        ok: '확인',
        yes: '예',
        no: '아니오',
        error: '오류',
        warning: '경고',
        info: '정보',
        success: '성공',
        'file.exists': '파일이 이미 존재합니다',
        'overwrite.confirm': '덮어쓰시겠습니까?',
        'delete.confirm': '정말 삭제하시겠습니까?',
        'operation.complete': '작업 완료',
        'operation.failed': '작업 실패',
        open: '열기',
        'open.with': '연결 프로그램',
        cut: '잘라내기',
        'copy.to': '복사 위치',
        'move.to': '이동 위치',
        properties: '속성',
        'search.placeholder': '파일 검색...',
        'search.results': '검색 결과',
        'no.results': '결과를 찾을 수 없습니다',
        settings: '설정',
        language: '언어',
        theme: '테마',
        'font.size': '글꼴 크기',
        'show.hidden': '숨김 파일 표시',
        'confirm.delete': '삭제 확인',
        save: '저장',
        terminal: '터미널',
        clear: '지우기',
        close: '닫기'
    },

    // Dutch
    nl: {
        'app.title': 'JaCommander',
        menu: 'Menu',
        'keyboard.shortcuts': 'Sneltoetsen',
        configuration: 'Configuratie',
        'toggle.theme': 'Thema wijzigen',
        'f1.help': 'F1 Help',
        'f2.menu': 'F2 Menu',
        'f3.view': 'F3 Bekijken',
        'f4.edit': 'F4 Bewerken',
        'f5.copy': 'F5 Kopiëren',
        'f6.move': 'F6 Verplaatsen',
        'f7.mkdir': 'F7 Map maken',
        'f8.delete': 'F8 Verwijderen',
        'f9.menu': 'F9 Menu',
        'f10.exit': 'F10 Afsluiten',
        'f11.terminal': 'F11 Terminal',
        'f12.settings': 'F12 Instellingen',
        name: 'Naam',
        size: 'Grootte',
        modified: 'Gewijzigd',
        items: 'items',
        selected: 'geselecteerd',
        copy: 'Kopiëren',
        move: 'Verplaatsen',
        delete: 'Verwijderen',
        rename: 'Hernoemen',
        'new.folder': 'Nieuwe map',
        'new.file': 'Nieuw bestand',
        refresh: 'Vernieuwen',
        search: 'Zoeken',
        'select.all': 'Alles selecteren',
        'deselect.all': 'Alles deselecteren',
        copying: 'Kopiëren',
        moving: 'Verplaatsen',
        deleting: 'Verwijderen',
        creating: 'Aanmaken',
        extracting: 'Uitpakken',
        compressing: 'Comprimeren',
        confirm: 'Bevestigen',
        cancel: 'Annuleren',
        ok: 'OK',
        yes: 'Ja',
        no: 'Nee',
        error: 'Fout',
        warning: 'Waarschuwing',
        info: 'Informatie',
        success: 'Succes',
        'file.exists': 'Bestand bestaat al',
        'overwrite.confirm': 'Wilt u overschrijven?',
        'delete.confirm': 'Weet u zeker dat u wilt verwijderen?',
        'operation.complete': 'Bewerking voltooid',
        'operation.failed': 'Bewerking mislukt',
        open: 'Openen',
        'open.with': 'Openen met',
        cut: 'Knippen',
        'copy.to': 'Kopiëren naar',
        'move.to': 'Verplaatsen naar',
        properties: 'Eigenschappen',
        'search.placeholder': 'Bestanden zoeken...',
        'search.results': 'Zoekresultaten',
        'no.results': 'Geen resultaten gevonden',
        settings: 'Instellingen',
        language: 'Taal',
        theme: 'Thema',
        'font.size': 'Lettergrootte',
        'show.hidden': 'Verborgen bestanden tonen',
        'confirm.delete': 'Verwijderen bevestigen',
        save: 'Opslaan',
        terminal: 'Terminal',
        clear: 'Wissen',
        close: 'Sluiten'
    },

    // Polish
    pl: {
        'app.title': 'JaCommander',
        menu: 'Menu',
        'keyboard.shortcuts': 'Skróty klawiaturowe',
        configuration: 'Konfiguracja',
        'toggle.theme': 'Zmień motyw',
        'f1.help': 'F1 Pomoc',
        'f2.menu': 'F2 Menu',
        'f3.view': 'F3 Podgląd',
        'f4.edit': 'F4 Edytuj',
        'f5.copy': 'F5 Kopiuj',
        'f6.move': 'F6 Przenieś',
        'f7.mkdir': 'F7 Nowy folder',
        'f8.delete': 'F8 Usuń',
        'f9.menu': 'F9 Menu',
        'f10.exit': 'F10 Wyjście',
        'f11.terminal': 'F11 Terminal',
        'f12.settings': 'F12 Ustawienia',
        name: 'Nazwa',
        size: 'Rozmiar',
        modified: 'Zmodyfikowany',
        items: 'elementy',
        selected: 'zaznaczono',
        copy: 'Kopiuj',
        move: 'Przenieś',
        delete: 'Usuń',
        rename: 'Zmień nazwę',
        'new.folder': 'Nowy folder',
        'new.file': 'Nowy plik',
        refresh: 'Odśwież',
        search: 'Szukaj',
        'select.all': 'Zaznacz wszystko',
        'deselect.all': 'Odznacz wszystko',
        copying: 'Kopiowanie',
        moving: 'Przenoszenie',
        deleting: 'Usuwanie',
        creating: 'Tworzenie',
        extracting: 'Wypakowywanie',
        compressing: 'Kompresowanie',
        confirm: 'Potwierdź',
        cancel: 'Anuluj',
        ok: 'OK',
        yes: 'Tak',
        no: 'Nie',
        error: 'Błąd',
        warning: 'Ostrzeżenie',
        info: 'Informacja',
        success: 'Sukces',
        'file.exists': 'Plik już istnieje',
        'overwrite.confirm': 'Czy chcesz nadpisać?',
        'delete.confirm': 'Czy na pewno chcesz usunąć?',
        'operation.complete': 'Operacja zakończona',
        'operation.failed': 'Operacja nieudana',
        open: 'Otwórz',
        'open.with': 'Otwórz za pomocą',
        cut: 'Wytnij',
        'copy.to': 'Kopiuj do',
        'move.to': 'Przenieś do',
        properties: 'Właściwości',
        'search.placeholder': 'Szukaj plików...',
        'search.results': 'Wyniki wyszukiwania',
        'no.results': 'Brak wyników',
        settings: 'Ustawienia',
        language: 'Język',
        theme: 'Motyw',
        'font.size': 'Rozmiar czcionki',
        'show.hidden': 'Pokaż ukryte pliki',
        'confirm.delete': 'Potwierdź usunięcie',
        save: 'Zapisz',
        terminal: 'Terminal',
        clear: 'Wyczyść',
        close: 'Zamknij'
    },

    // Turkish
    tr: {
        'app.title': 'JaCommander',
        menu: 'Menü',
        'keyboard.shortcuts': 'Klavye Kısayolları',
        configuration: 'Yapılandırma',
        'toggle.theme': 'Tema Değiştir',
        'f1.help': 'F1 Yardım',
        'f2.menu': 'F2 Menü',
        'f3.view': 'F3 Görüntüle',
        'f4.edit': 'F4 Düzenle',
        'f5.copy': 'F5 Kopyala',
        'f6.move': 'F6 Taşı',
        'f7.mkdir': 'F7 Klasör',
        'f8.delete': 'F8 Sil',
        'f9.menu': 'F9 Menü',
        'f10.exit': 'F10 Çıkış',
        'f11.terminal': 'F11 Terminal',
        'f12.settings': 'F12 Ayarlar',
        name: 'Ad',
        size: 'Boyut',
        modified: 'Değiştirilme',
        items: 'öğe',
        selected: 'seçildi',
        copy: 'Kopyala',
        move: 'Taşı',
        delete: 'Sil',
        rename: 'Yeniden Adlandır',
        'new.folder': 'Yeni Klasör',
        'new.file': 'Yeni Dosya',
        refresh: 'Yenile',
        search: 'Ara',
        'select.all': 'Tümünü Seç',
        'deselect.all': 'Tümünü Bırak',
        copying: 'Kopyalanıyor',
        moving: 'Taşınıyor',
        deleting: 'Siliniyor',
        creating: 'Oluşturuluyor',
        extracting: 'Ayıklanıyor',
        compressing: 'Sıkıştırılıyor',
        confirm: 'Onayla',
        cancel: 'İptal',
        ok: 'Tamam',
        yes: 'Evet',
        no: 'Hayır',
        error: 'Hata',
        warning: 'Uyarı',
        info: 'Bilgi',
        success: 'Başarılı',
        'file.exists': 'Dosya zaten mevcut',
        'overwrite.confirm': 'Üzerine yazmak istiyor musunuz?',
        'delete.confirm': 'Silmek istediğinizden emin misiniz?',
        'operation.complete': 'İşlem tamamlandı',
        'operation.failed': 'İşlem başarısız',
        open: 'Aç',
        'open.with': 'Birlikte Aç',
        cut: 'Kes',
        'copy.to': 'Kopyala',
        'move.to': 'Taşı',
        properties: 'Özellikler',
        'search.placeholder': 'Dosya ara...',
        'search.results': 'Arama Sonuçları',
        'no.results': 'Sonuç bulunamadı',
        settings: 'Ayarlar',
        language: 'Dil',
        theme: 'Tema',
        'font.size': 'Yazı Boyutu',
        'show.hidden': 'Gizli Dosyaları Göster',
        'confirm.delete': 'Silmeyi Onayla',
        save: 'Kaydet',
        terminal: 'Terminal',
        clear: 'Temizle',
        close: 'Kapat'
    },

    // Arabic
    ar: {
        'app.title': 'JaCommander',
        menu: 'القائمة',
        'keyboard.shortcuts': 'اختصارات لوحة المفاتيح',
        configuration: 'الإعدادات',
        'toggle.theme': 'تغيير الثيم',
        'f1.help': 'F1 مساعدة',
        'f2.menu': 'F2 قائمة',
        'f3.view': 'F3 عرض',
        'f4.edit': 'F4 تحرير',
        'f5.copy': 'F5 نسخ',
        'f6.move': 'F6 نقل',
        'f7.mkdir': 'F7 مجلد جديد',
        'f8.delete': 'F8 حذف',
        'f9.menu': 'F9 قائمة',
        'f10.exit': 'F10 خروج',
        'f11.terminal': 'F11 محطة',
        'f12.settings': 'F12 إعدادات',
        name: 'الاسم',
        size: 'الحجم',
        modified: 'معدل',
        items: 'عناصر',
        selected: 'محدد',
        copy: 'نسخ',
        move: 'نقل',
        delete: 'حذف',
        rename: 'إعادة تسمية',
        'new.folder': 'مجلد جديد',
        'new.file': 'ملف جديد',
        refresh: 'تحديث',
        search: 'بحث',
        'select.all': 'تحديد الكل',
        'deselect.all': 'إلغاء تحديد الكل',
        copying: 'جارٍ النسخ',
        moving: 'جارٍ النقل',
        deleting: 'جارٍ الحذف',
        creating: 'جارٍ الإنشاء',
        extracting: 'جارٍ الاستخراج',
        compressing: 'جارٍ الضغط',
        confirm: 'تأكيد',
        cancel: 'إلغاء',
        ok: 'موافق',
        yes: 'نعم',
        no: 'لا',
        error: 'خطأ',
        warning: 'تحذير',
        info: 'معلومات',
        success: 'نجاح',
        'file.exists': 'الملف موجود بالفعل',
        'overwrite.confirm': 'هل تريد الكتابة فوقه؟',
        'delete.confirm': 'هل أنت متأكد من الحذف؟',
        'operation.complete': 'اكتملت العملية',
        'operation.failed': 'فشلت العملية',
        open: 'فتح',
        'open.with': 'فتح باستخدام',
        cut: 'قص',
        'copy.to': 'نسخ إلى',
        'move.to': 'نقل إلى',
        properties: 'الخصائص',
        'search.placeholder': 'البحث عن ملفات...',
        'search.results': 'نتائج البحث',
        'no.results': 'لم يتم العثور على نتائج',
        settings: 'الإعدادات',
        language: 'اللغة',
        theme: 'الثيم',
        'font.size': 'حجم الخط',
        'show.hidden': 'إظهار الملفات المخفية',
        'confirm.delete': 'تأكيد الحذف',
        save: 'حفظ',
        terminal: 'محطة',
        clear: 'مسح',
        close: 'إغلاق'
    }
};

// Language metadata
export const languageMetadata = {
    en: { flag: '🇬🇧', code: 'EN', name: 'English', nativeName: 'English' },
    es: { flag: '🇪🇸', code: 'ES', name: 'Spanish', nativeName: 'Español' },
    de: { flag: '🇩🇪', code: 'DE', name: 'German', nativeName: 'Deutsch' },
    fr: { flag: '🇫🇷', code: 'FR', name: 'French', nativeName: 'Français' },
    it: { flag: '🇮🇹', code: 'IT', name: 'Italian', nativeName: 'Italiano' },
    pt: { flag: '🇵🇹', code: 'PT', name: 'Portuguese', nativeName: 'Português' },
    ru: { flag: '🇷🇺', code: 'RU', name: 'Russian', nativeName: 'Русский' },
    zh: { flag: '🇨🇳', code: 'ZH', name: 'Chinese', nativeName: '中文' },
    ja: { flag: '🇯🇵', code: 'JA', name: 'Japanese', nativeName: '日本語' },
    ko: { flag: '🇰🇷', code: 'KO', name: 'Korean', nativeName: '한국어' },
    nl: { flag: '🇳🇱', code: 'NL', name: 'Dutch', nativeName: 'Nederlands' },
    pl: { flag: '🇵🇱', code: 'PL', name: 'Polish', nativeName: 'Polski' },
    tr: { flag: '🇹🇷', code: 'TR', name: 'Turkish', nativeName: 'Türkçe' },
    ar: { flag: '🇸🇦', code: 'AR', name: 'Arabic', nativeName: 'العربية' }
};

export default languagePack;
